version: '3'

services:
  nginx:
    image: nginx:1.15.9
    container_name: ng
    ports:
      - "8080:8000"
    volumes:
      - ./NVD:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    build: .
    container_name: api
    command: ['./scripts/wait-for-postgres.sh', 'db', './scripts/run_server.sh']
    environment:
      POSTGRES_PASSWORD: "postgres"
    depends_on:
      - db
    volumes:
      - .:/src
    expose:
      - "8000"

  db:
    image: postgres:11
    container_name: pg
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "NVD"