# Generated by Django 2.1.5 on 2019-02-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVE',
        ),
    ]
