# Generated by Django 2.1.5 on 2019-03-11 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_cve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.TextField(unique=True)),
                ('vendors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('cwes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('cpes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('impact', models.TextField()),
                ('published_date', models.TextField()),
                ('last_modified_date', models.TextField()),
            ],
        ),
    ]
