# Generated by Django 2.1.5 on 2019-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_cve'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearsVulnerabilitiesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('vulnerabilities_count', models.IntegerField()),
            ],
        ),
    ]
