# Generated by Django 2.1.5 on 2019-04-07 10:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_yearsvulnerabilitiescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='impact',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
