# Generated by Django 2.1.5 on 2019-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190407_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostVulnerableVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField()),
                ('vulnerabilities_count', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
