# Generated by Django 2.1.5 on 2019-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190604_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
